### ISSUE TITLE
需要测试的caddy 工作在openwrt

### ISSUE THREAD

**Issue by fuqiang03** [lmq8267/luci-app-caddy#1]
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=caddy
PKG_VERSION:=2.7.6
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/caddyserver/caddy/tar.gz/v$(PKG_VERSION)?
PKG_HASH:=e1c524fc4f4bd2b0d39df51679d9d065bb811e381b7e4e51466ba39a0083e3ed

PKG_LICENSE:=GPL-3.0-or-later
PKG_LICENSE_FILES:=LICENSE

PKG_BUILD_DEPENDS:=golang/host upx/host
PKG_BUILD_PARALLEL:=1
PKG_BUILD_FLAGS:=no-mips16

GO_PKG:=github.com/caddyserver/caddy/v2/cmd
GO_PKG_BUILD_PKG:=$(GO_PKG)/caddy
GO_PKG_LDFLAGS:=-s -w

include $(INCLUDE_DIR)/package.mk
include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk

define Package/$(PKG_NAME)
  TITLE:=Caddy xxxxxxxxxxx
  URL:=https://caddyserver.com
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Web Servers/Proxies
  DEPENDS:=$(GO_ARCH_DEPENDS) +libpthread
endef

define Package/$(PKG_NAME)/description
Caddy xxxxxxxx.
endef

define Build/Compile
	$(call GoPackage/Build/Compile)
	$(STAGING_DIR_HOST)/bin/upx --lzma --best $(GO_PKG_BUILD_BIN_DIR)/caddy
endef

$(eval $(call GoBinPackage,$(PKG_NAME)))
$(eval $(call BuildPackage,$(PKG_NAME)))

使用ARM7 构架 生成文件大约在9m

**Comment by lmq8267** [comment]
我的是mipsel架构的 编译后体积大约7.5M

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/04b8cb97-01a6-45dc-a688-3de8855e667d)

openwrt main库 luci 最新版

**Comment by lmq8267** [comment]
fs忘记删了  你需要安装需要安装luci-lib-fs


> ![图像](https://private-user-images.githubusercontent.com/26851715/298057525-04b8cb97-01a6-45dc-a688-3de8855e667d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjYzNDYsIm5iZiI6MTcwNTY2NjA0NiwicGF0aCI6Ii8yNjg1MTcxNS8yOTgwNTc1MjUtMDRiOGNiOTctMDFhNi00NWRjLWE2ODgtM2RlODg1NWU2NjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyMDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhODYyNmJlNjhkYWY0YWExOTY4YTJhNjhmMjBkOWFhODU2ZTg4ZmU3OTUxZTRiODU0MTE0MzE5OGYyMTQzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y84F05EU543h3-5HsXvHBCPWD_IegWeBsWGkHgEJYk0)
> 
> openwrt main库 luci 最新版本

**Comment by lmq8267** [comment]
有个fs  忘记删了    需要安装luci-lib-lib才能显示   我现在去删了那个没用的fs

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/16ec7aad-d414-4d62-9948-f31dfa7bf172)
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/6dae29e2-9627-4e04-a077-52e30584e3d4)
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/fc8ba590-268e-47e9-a26c-e1e5551c86f5)
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/565882f5-a6e8-49e1-bee5-a01b6e85166c)

**Comment by lmq8267** [comment]
需要上传程序  设置好程序路径

**Comment by fuqiang03** [comment]
日志路径创建了 文件路径也准备好了

**Comment by lmq8267** [comment]
你可以直接填程序路径 不用   运行报错那个是填写的路径里没有找到程序/usr/bin/caddy

**Comment by fuqiang03** [comment]
已经可以了  谢谢了

**Comment by fuqiang03** [comment]
Fri 1月19日 21:31:53 2024 daemon.err uhttpd[2809]: date: invalid date '@' 这个问题是由下图位置发出的 ![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/c1353b69-65ea-4979-a991-6ac087a9ce37)
shell文件 无法在控制页面执行 只能使用命令

**Comment by lmq8267** [comment]
我的是没有任何问题也没有任何报错  那里可以添加shell命令的  我也不知道是不是 luci-compat 包的原因 我安装了这些包 我的是openwrt 官方23.05的版本   mipsel架构的
![QQ截图20240119214854](https://github.com/lmq8267/luci-app-caddy/assets/119713693/d345a4e9-4294-4f66-8a08-98c9276a9c94)
![QQ截图20240119215001](https://github.com/lmq8267/luci-app-caddy/assets/119713693/3833ab84-1c4a-4a52-a09a-896b2ef07433)


还有启动不了 是通过Makefile构建的二进制程序没有添加webdav模块 只要不开启webdav就能启动

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/51dc4d86-d57d-43b8-ad48-09c865dd71c8)
估计是luci的问题

**Comment by lmq8267** [comment]
大概是这俩把   luci-base 和 luci-compat  这两个好像luci常用的

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/0a3718c5-b96b-41d5-bc55-af88f02b7ca5)
我试了下 就这个@闹的

**Comment by lmq8267** [comment]
@和$time不能有空格的      必须@$time

**Comment by lmq8267** [comment]
![QQ截图20240119235755](https://github.com/lmq8267/luci-app-caddy/assets/119713693/e91d5c15-bb34-4642-b2fd-58d1a1fba554)

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/29ac0f04-a521-40be-9bdc-132758387f6f)
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/f0b97c37-af7b-4f76-aec3-fe211dc3e3d3)
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/ee0f8bd7-1cd7-4368-9a22-71b554db96de)
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/fb07452e-94f9-408d-9885-530a62c19558)
Sat Jan 20 13:06:17 2024 daemon.err uhttpd[2811]: {"level":"warn","ts":1705727177.5936818,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
Sat Jan 20 13:06:20 2024 daemon.err uhttpd[2811]: date: invalid date '@'
Sat Jan 20 13:07:49 2024 daemon.err uhttpd[2811]: {"level":"warn","ts":1705727269.2001436,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}-------------------------------  
能在新版的 luci下 用控制页面 启动了
启动成功后 date: invalid date '@ 这条语句就消失了 在未启动的情况下 访问控制页面就会 一直刷新这条语句

**Comment by lmq8267** [comment]
已经修改好了 不会再出现这个了  你试试新的看看

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/fcf8a6e9-0a7c-4feb-a288-fcfe606c04b6)
我的目前没有问题了 适应新版的luci

添加版本号
GO_PKG:=github.com/caddyserver/caddy/v2/cmd
GO_PKG_BUILD_PKG:=$(GO_PKG)/caddy
GO_PKG_LDFLAGS:=-s -w
GO_PKG_LDFLAGS_X:=github.com/caddyserver/caddy/v2.CustomVersion=v$(PKG_VERSION)

**Comment by fuqiang03** [comment]
有什么命令可以查看caddy 里面 加成什么插件吗

**Comment by lmq8267** [comment]
好像不能看吧？ 我也不懂  对这个不熟悉

**Comment by fuqiang03** [comment]
![1111](https://github.com/lmq8267/luci-app-caddy/assets/26851715/3cd3d571-bbb4-4571-94d4-586c39d1a52e)
![222](https://github.com/lmq8267/luci-app-caddy/assets/26851715/829be925-2775-4c45-af0e-9f2c4b5b639c)
这样算是成功吗
[caddy.zip](https://github.com/lmq8267/luci-app-caddy/files/14084737/caddy.zip)
我只是简单运行了下  能正常打开

--with github.com/aksdb/caddy-cgi/v2 
这个需要下次做了

**Comment by lmq8267** [comment]
我也不懂 我只用到了文件服务器这一个功能 你图片里那个是可以查看添加了哪些插件吗？

**Comment by fuqiang03** [comment]
build-info    // Prints information about this build  
应该在开发下其他的功能 看了下帮助文档 这个文件还是很强大的

**Comment by lmq8267** [comment]
这个命令可以列出集成了哪些插件
`caddy list-modules --packages`

**Comment by fuqiang03** [comment]
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/91b4840b-a2bd-40aa-819b-619f6ffe67d8)
看到了

**Comment by lmq8267** [comment]
打印caddy的构建信息
`caddy build-info`

来自[Caddy实战（二）| Caddy命令行参数最全教程](https://zhuanlan.zhihu.com/p/405927899)

**Comment by fuqiang03** [comment]
额 没有注意到 下面的 命令参数
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/44b5b01b-fdc3-4cc2-b663-74ea39adf0b4)
想把这个代理功能集成到路由器中 这样就方便上giehub了

**Comment by lmq8267** [comment]
代理？ 如何操作？需要额外加插件支持吗?   配置文件中怎么添加

**Comment by fuqiang03** [comment]
问一下 你的用什么型号路由器
我用的是官方执行文件
https://www.dogfight360.com/blog/686/  下面有个专项 
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/5365b4b5-6fa9-4a4e-9c72-297f94ce6a97)

**Comment by lmq8267** [comment]
用的是mipsel的k2p路由器   openwrt 23.05 自己编译的caddy二进制文件

**Comment by fuqiang03** [comment]
二进制文件放在固件中?    k2p  曾经的金融 啊   这都多少年了

**Comment by lmq8267** [comment]
改了USB  放在usb存储里运行的

**Comment by fuqiang03** [comment]
哦哦 我的内存都被 二进制文件占用了
![image](https://github.com/lmq8267/luci-app-caddy/assets/26851715/7be539c4-646e-4aef-96d1-ef041320f438)

**Comment by lmq8267** [comment]
>  https://www.dogfight360.com/blog/686/ 下面有一个专门 ![图像](https://private-user-images.githubusercontent.com/26851715/300789284-5365b4b5-6fa9-4a4e-9c72-297f94ce6a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjA2OTAsIm5iZiI6MTcwNjYyMDM5MCwicGF0aCI6Ii8yNjg1MTcxNS8zMDA3ODkyODQtNTM2NWI0YjUtNmZhOS00YTRlLTljNzItMjk3Zjk0Y2U2YTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEzMTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmIxOGMxOWRkY2QyMmVjMjliOThlMjg2NjExMzdlNjgzM2E5MTNlMTY1ODhkNDVhMTcwMmU4YmJhMmI3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhCZ0O4jAQIX4O6liQ8mZGu0QTthBk8YwbpUsNmJ5VE)

不是很懂这个是啥  不过你可以使用自定义配置文件 填入这些  可以实现的

**Comment by fuqiang03** [comment]
想弄个 在路由器有控制页面的 在Linux 没有 按照他的说法没有配置文件的

**Comment by lmq8267** [comment]
![QQ截图20240130214235](https://github.com/lmq8267/luci-app-caddy/assets/119713693/cedf0dbc-79cb-4b9b-bd33-f972a8394a67)
他这个就是配置文件吧 按照他的复制到路由器的配置文件里

这样应该可以吧
![QQ截图20240130214557](https://github.com/lmq8267/luci-app-caddy/assets/119713693/88e2beec-683e-4afa-a6f1-2b17a914ddc8)

**Comment by lmq8267** [comment]
好像是需要先在电脑下载他的程序  用来生成配置文件

![QQ截图20240130215541](https://github.com/lmq8267/luci-app-caddy/assets/119713693/860a8507-ec40-4414-a3fe-a86a951b361d)

这样点击之后
就会生成这个caddy的配置

![QQ截图20240130215557](https://github.com/lmq8267/luci-app-caddy/assets/119713693/5cb4f436-313c-4df7-98bd-c159959e476b)

然后全部复制进去路由器配置文件里把？

![QQ截图20240130215613](https://github.com/lmq8267/luci-app-caddy/assets/119713693/b3d53507-2c73-4f8c-bde7-3fcbc7beb525)
![QQ截图20240130215657](https://github.com/lmq8267/luci-app-caddy/assets/119713693/810e0b4a-6ab8-409b-aebd-93adf70da1f8)


可以使用命令检测这个配置是否正确 
`caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile`

**Comment by fuqiang03** [comment]
好的  我试试

**Comment by lmq8267** [comment]
看他的安装脚本 好像还需要把这个证书也要复制进去  配置文件里的也要修改正确的tsl路径吧？
![QQ截图20240130220807](https://github.com/lmq8267/luci-app-caddy/assets/119713693/f675663b-3619-42af-b352-83ff50e0db5a)
有很多个，不知道是否都需要修改为绝对路径，比如你上传到/etc/caddy/*里  这里是不是要改成/etc/caddy/steamcommunity.crt
![QQ截图20240130221006](https://github.com/lmq8267/luci-app-caddy/assets/119713693/699c3af4-c627-4501-8024-679dc56e9c11)


以及还要修改hosts？

**Comment by fuqiang03** [comment]
正常证书要跟 二进制文件一起 在Ubuntu里执行需要修改hosts 和 添加证书

**Comment by lmq8267** [comment]
那openwrt也是一样的吧    填写好配置文件 还需要把证书放进去 也要修改hosts了

**Comment by fuqiang03** [comment]
所以这样操作就麻烦了 想弄个控制页面 直接开启就好了

**Comment by lmq8267** [comment]
我还不懂他的原理   这个还是需要他的电脑生成再复制进去的  我也不知道怎么配置的 为什么必须得他的这个软件生成才行

**Comment by fuqiang03** [comment]
这个我也不清楚的 也没在Windows下看到caddy 文件  但是在Ubuntu 上必须使用caddy

**Comment by lmq8267** [comment]
有啊  他的压缩包里 有个win的caddy程序

**Comment by fuqiang03** [comment]
扩展名是caddy的  我都有网扩展名上看

**Comment by fuqiang03** [comment]
[caddy.zip](https://github.com/lmq8267/luci-app-caddy/files/14156470/caddy.zip)
二进制文件完成 两个插件都添加了  构建环境使用openwrt 最新官方源码 其中upx 依赖 自行从ImmortalWrt.org 源码中提取
文件8.67M 感觉还是有点大
